image: maven:3.9.14-eclipse-temurin-25-alpine

workflow:
  rules:
    # If it's a merge request, run the MR pipeline
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

    # If it's a push to a branch, but there is an open MR for this branch,
    # DON'T run a second pipeline.
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never

    # Otherwise, run for pushes to branches (like main)
    - if: '$CI_COMMIT_BRANCH'

stages:
  - verify
  - site
  - pages
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

before_script:
  - mvn -B dependency:go-offline
  - mvn -v

# --- validate (style, coverage, complexity) ---
verify:
  stage: verify
  script:
    - mvn -B verify
  artifacts:
    when: always
    paths:
      - target/*
    reports:
      junit: target/surefire-reports/TEST-*.xml
    expire_in: 30 mins

# --- site ---
site:
  stage: site
  needs:
    - job: verify
      artifacts: true
  script:
    - mvn -B site
  artifacts:
    when: always
    paths:
      - target/site
    expire_in: 30 mins
  when: always

# --- pages ---
pages:
  stage: pages
  needs:
    - job: site
      artifacts: true
  script:
    - mv target/site public
  artifacts:
    paths:
      - public
  when: always

# --- build (only on main merges) ---
build:
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
