package ch.fhnw.roundtable.etopia.views;

// todo rename
public enum ViewType {
    MAP,
    INFORMATION,
    SETTINGS,

    BIOGAS,
    BIOGAS_START,
    BIOGAS_SUCCESS,
    BIOGAS_FAIL_HEALTH,

    WIND,
    WIND_START,
    WIND_SUCCESS,
    WIND_FAIL_HEALTH,
    WIND_FAIL_CLOCK,

    GEOTHERMAL,
    GEOTHERMAL_START,
    GEOTHERMAL_SUCCESS,
    GEOTHERMAL_FAIL_HEALTH,

    SOLAR,
    SOLAR_START,
    SOLAR_SUCCESS,
    SOLAR_FAIL_CLOCK,

    GRID,
    GRID_START,
    GRID_SUCCESS,
    GRID_FAIL_CLOCK
}
