map.infopanel.wind.title = Wind
map.infopanel.wind.description = Sammle angemessene Mengen an Wind
map.infopanel.biomass.title = Biomasse
map.infopanel.biomass.description = Sammle angemessene Objekte
map.infopanel.start = Start: Leertaste
map.infotext = Select [Enter/Space], Back [Backspace/Esc], Move [Arrows/WASD]