# Languages need to be the folder ./configuration, same as 'app.properties'
#           configuration:  <language>,<language>,<language> (comma separated, no spaces)
#           filename:       <language>.properties
languages = deutsch,english
dummyMode = false
fullScreen = true

information.disabledDuration = 3.0

status.totalHealth = 5
status.animatedIconsSize = 40

map.doSettingPulse = true

biogas.gameDuration = 60
biogas.conveyorSpeed = 1.0
biogas.animatedOnConveyor = true
biogas.useAnimatedIcons = true
biogas.powerPercentPerTrash = 0.06

wind.turbineSpeed = 400
wind.gustSpeed = 600
wind.gameDuration = 30
wind.freezeCountdown = 1.0
wind.gustTimer = 0.5
wind.tornadoTimer = 0.8
wind.energyAdded = 0.05
wind.useAnimatedIcons = true

solar.panelSpeed = 75.0
solar.panelMaxRotation = 70.0
solar.sunSpeed = 0.7
solar.gameDuration = 45.0
solar.energyInterval = 0.5

geothermal.gameDuration = 120.0
geothermal.drillSpeed = 400.0
geothermal.numberOfRocks = 40
geothermal.collisionCountdown = 2.0
geothermal.bottomCountdown = 1.0
geothermal.topCountdown = 1.0
geothermal.useAnimatedIcons = true

grid.mapWidth = 28
grid.mapHeight = 16
grid.gameDuration = 60.0
grid.finishCountdown = 2.0
grid.animatedPipeRotation = true

