# Languages need to be the folder ./configuration, same as 'app.properties'
#           configuration:  <language>,<language>,<language> (comma separated, no spaces)
#           filename:       <language>.properties
languages = german,english

wind.turbineSpeed = 400
wind.gustSpeed = 600
