# Languages need to be the folder ./configuration, same as 'app.properties'
#           configuration:  <language>,<language>,<language> (comma separated, no spaces)
#           filename:       <language>.properties
languages = deutsch,english
dummyMode = false
fullScreen = true

status.animatedIconsSize = 40

biogas.gameDuration = 60
biogas.conveyorSpeed = 1.0
biogas.powerPercentPerTrash = 0.5
biogas.animatedOnConveyor = true
biogas.useAnimatedIcons = true

wind.useAnimatedIcons = true

grid.animatedPipeRotation = true
